TAG ?= latest
NS ?= dhf0820
APP_NAME := uc_blaze

.PHONY: build run stop clean

build:
	@docker compose build --build-arg TAG=$(TAG)

push:
	@docker push $(NS)/$(APP_NAME):$(TAG)

run:
	@docker stack deploy --compose-file docker-compose.yml $(APP_NAME)



clean:
	@docker system prune --volumes --force
